### ISSUE TITLE
New-IntuneWin32AppIcon: Cannot validate argument on parameter 'FilePath'. File or folder does not exist

### ISSUE THREAD

**Issue by groupk-frankkeunen** [NicklasAhlberg/RockMyPrinters#3]
Hi,

When importing the package into Intune, the following error is thrown:

**********************
PS>TerminatingError(New-IntuneWin32AppIcon): "Cannot validate argument on parameter 'FilePath'. File or folder does not exist"
>> TerminatingError(New-IntuneWin32AppIcon): "Cannot validate argument on parameter 'FilePath'. File or folder does not exist"
**********************

**Comment by NicklasAhlberg** [comment]
Hi,

The logos are found here: "Tools\_logos" could you please make sure that they are there and that you have downloaded the latest version of the tool? 

Do note that I am about to release a new version of the tool in close future. Please look for it and let me know how it goes.

best regards

Nicklas

**Comment by NicklasAhlberg** [comment]
Hi, please try v1.0.1.4 (latest release) :)

//Nicklas

**Comment by BryceAtSabre** [comment]
Hi, I think this problem is caused by a bad dependency.
RockMyPrinters seems to use IntuneWinAppUtil.exe located in %userprofile%/Appdata/Local/Temp/ folder.
V1.8.5 of Microsoft-Win32-Content-Prep-Tool seems to be having issues. Replacing that executable with a previous version like V1.8.4 seems to work just fine.

**Comment by NicklasAhlberg** [comment]
Have not heard back. Let me know if this still doesn't work.

//Nicklas
